(()=>{'use strict';
const scriptURL=document.currentScript.src,baseURL=new URL('./',scriptURL),KEY='crd_landing_xv',DRAFT=KEY+'_draft';
let bridge,base,fields,config,iframe,dirty=false,loaded=false,loading=false,saveBusy=false,loadFailed=false;
const root=()=>document.getElementById('landing-admin-root');
function status(text,error=false){const el=document.getElementById('la-status');if(el){el.textContent=text;el.classList.toggle('error',error)}}
function preview(){iframe?.contentWindow?.postMessage({type:'landing-preview',config},location.origin)}
function draft(){dirty=true;try{localStorage.setItem(DRAFT,JSON.stringify(config));status('Cambios sin publicar. Borrador guardado en este navegador.')}catch{status('Cambios sin publicar. No se pudo guardar el borrador local.',true)}preview()}
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text)node.textContent=text;return node}
function button(text,fn,primary=false){const b=el('button','la-button'+(primary?' primary':''),text);b.type='button';b.addEventListener('click',fn);return b}
function field(parent,label,value,set,kind='text'){const box=el('label','la-field'),title=el('span','',label);const input=el(kind==='textarea'?'textarea':'input');if(kind!=='textarea')input.type=kind==='image'||kind==='video'?'text':kind;input.value=value??'';if(kind==='number'){input.min='0';input.max='100'}input.addEventListener('input',()=>{set(input.value);draft()});box.append(title,input);parent.append(box);
if(['image','video'].includes(kind)){input.placeholder=kind==='video'?'Pegá el enlace del video de Drive':'Pegá el enlace de la imagen de Drive';const actions=el('div','la-media-actions');actions.append(button('Elegir de Drive',()=>{bridge.pickDrive((url,name)=>{const isVideo=/\.(mp4|mov|webm|m4v|avi|mkv)$/i.test(name||'');if(kind==='image'&&isVideo){status('Elegí una imagen para este campo.',true);return}if(kind==='video'&&name&&/\.(jpe?g|png|webp|gif|heic)$/i.test(name)){status('Elegí un video para este campo.',true);return}const id=LandingModel.driveId(url);const selected=id?'https://drive.google.com/file/d/'+id.id+'/view':url;input.value=selected;set(selected);draft();updateThumb()})}));if(kind==='video')actions.append(button('Quitar video',()=>{input.value='';set('');draft()}));box.append(actions);const hint=el('p','la-hint',kind==='video'?'Elegí un video de Drive. Debe permitir acceso a cualquier persona con el enlace. Se reproduce al tocar su portada.':'Elegí una imagen accesible para cualquier persona con el enlace.');box.append(hint);var thumb;if(kind==='image'){thumb=el('img');thumb.alt='Vista previa';box.append(thumb);input.addEventListener('change',updateThumb);updateThumb()}function updateThumb(){if(thumb){const url=LandingModel.imageURL(input.value,baseURL.href);thumb.hidden=!url;if(url)thumb.src=url}}}
return input;}
function group(container,title){const details=el('details');details.append(el('summary','',title));container.append(details);return details}
function build(){const host=root();host.replaceChildren();const head=el('div','la-head');const title=el('div');title.append(el('h2','','Landing'),el('p','','XV · Editá tu página de campañas. Los cambios aparecen en la vista previa; publicalos cuando estén listos.'));head.append(title);host.append(head);const toolbar=el('div','la-toolbar');toolbar.append(button('Guardar borrador',draft),button('Publicar cambios',save,true),button('Recargar publicado',reload));const link=el('a','la-button','Abrir landing');link.href=baseURL.href;link.target='_blank';link.rel='noopener';toolbar.append(link);host.append(toolbar);const msg=el('p','la-status');msg.id='la-status';msg.setAttribute('role','status');host.append(msg);
const layout=el('div','la-layout'),editor=el('div','la-editor'),view=el('aside','la-preview mobile');layout.append(editor,view);host.append(layout);
const general=group(editor,'Diseño, logo y título de la página');general.open=true;field(general,'Logo',config.logo,v=>config.logo=v,'image');field(general,'Título de la pestaña',config.seo.title,v=>config.seo.title=v);field(general,'Descripción de la página',config.seo.description,v=>config.seo.description=v,'textarea');for(const [key,label] of Object.entries({bg:'Fondo',panel:'Tarjetas',gold:'Acento',ink:'Texto principal',muted:'Texto secundario'}))field(general,label,config.colors[key],v=>config.colors[key]=v,'color');
const bot=group(editor,'RomeBot · Asistente de servicios');
const botLabel=el('label','la-field'),botToggle=el('input');botToggle.type='checkbox';botToggle.checked=config.bot.enabled!==false;botToggle.addEventListener('change',()=>{config.bot.enabled=botToggle.checked;draft()});botLabel.append(botToggle,document.createTextNode('Mostrar RomeBot en la landing'));bot.append(botLabel);
for(const [key,label] of Object.entries({label:'Texto del botón',welcome:'Saludo de bienvenida',prices:'Precios e impuestos confirmados',booking:'Reserva de cita y disponibilidad',delivery:'Entregas, pagos y condiciones confirmadas',weddings:'Información confirmada de bodas',extra:'Otras preguntas y respuestas (separá cada tema con una línea vacía)',fallback:'Respuesta cuando falta información'}))field(bot,label,config.bot[key],v=>config.bot[key]=v,key==='label'?'text':'textarea');
bot.append(el('p','la-help','RomeBot toma las prestaciones de los packs que editás aquí. Completá solo información comercial confirmada. Los campos vacíos derivan la consulta a Cristian. La vista previa usa la guía de servicios y no consume IA.'));
const connection=group(bot,'Conexión de IA');field(connection,'Dirección del servicio de RomeBot',config.bot.endpoint,v=>config.bot.endpoint=v);connection.append(el('p','la-help','Dejá vacío para usar la guía de servicios. Para respuestas conversacionales, agregá la URL HTTPS del servicio de IA una vez activado. No pegues claves de API en este campo.'));
const videos=group(editor,'Videos desde Google Drive');for(const [key,label] of Object.entries({presentacion:'Presentación de Cristian',event:'CR Event',portrait:'CR Portrait',editorial:'CR Editorial',cinematic:'CR Cinematic'})){field(videos,label,config.videos[key],v=>config.videos[key]=v,'video');field(videos,'Texto del reproductor · '+label,config.videoLabels[key],v=>config.videoLabels[key]=v)}
const messages=group(editor,'Formulario: títulos y respuestas');for(const [key,label] of Object.entries({citaTitle:'Título para reservar cita',citaDescription:'Presentación para cita',citaSuccess:'Confirmación de solicitud de cita',infoTitle:'Título para pedir información',infoDescription:'Presentación para información',infoSuccess:'Confirmación de consulta',error:'Mensaje si falla el envío'}))field(messages,label,config.form[key],v=>config.form[key]=v,'textarea');messages.append(el('p','la-help','Los formularios usan el servicio de correo ya configurado en el sitio. La cita se solicita y se coordina por email; no confirma un horario automáticamente.'));
for(const [key,name] of LandingModel.groups){const section=group(editor,name);if(!['brand','hero','contact','footer','form'].includes(key)){const label=el('label','la-field'),check=el('input');check.type='checkbox';check.checked=!config.hidden[key];check.addEventListener('change',()=>{config.hidden[key]=!check.checked;draft()});label.append(check,document.createTextNode('Mostrar esta sección'));section.append(label)}for(const f of fields.filter(x=>x.group===key))field(section,f.label,config.values[f.key],v=>config.values[f.key]=v,f.kind)}
const previewbar=el('div','la-toolbar');previewbar.append(button('Celular',()=>view.classList.add('mobile')),button('Escritorio',()=>view.classList.remove('mobile')));view.append(previewbar);iframe=el('iframe');iframe.title='Vista previa de la landing de XV';iframe.src=new URL('?preview=1',baseURL).href;iframe.addEventListener('load',preview);view.append(iframe);status('Contenido cargado.');}
async function read(url,headers={}){const r=await fetch(url,{headers,cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('No se pudo leer la configuración ('+r.status+').');return r.json()}
async function readPublished(){// La lectura pública es la versión que está viendo el visitante.
return read(bridge.cfURL+'/'+KEY);}
async function open(context){bridge=context;if(loaded||loading)return;loading=true;root().textContent='Cargando Landing…';try{const r=await fetch(new URL('index.html',baseURL),{cache:'no-store'});if(!r.ok)throw Error('No se pudo cargar la plantilla de la landing.');const doc=new DOMParser().parseFromString(await r.text(),'text/html');fields=LandingModel.collect(doc);base=LandingModel.defaults(doc);let published,warning='';try{published=await readPublished()}catch{warning='No se pudo leer la versión publicada. Mostramos la base; recargá antes de publicar.'}config=LandingModel.merge(base,published);build();loaded=true;if(warning){status(warning,true);loadFailed=true}let cached;try{cached=JSON.parse(localStorage.getItem(DRAFT))}catch{}if(cached?.version===1){const toolbar=root().querySelector('.la-toolbar');toolbar.append(button('Recuperar borrador local',()=>{config=LandingModel.merge(base,cached);dirty=true;build();draft()}))}}catch(error){root().textContent=error.message;loaded=false}finally{loading=false}}
async function reload(){if(dirty&&!confirm('¿Descartar los cambios sin publicar y cargar la versión publicada?'))return;try{const published=await readPublished();config=LandingModel.merge(base,published);loadFailed=false;dirty=false;build();status('Versión publicada cargada.')}catch(e){status(e.message,true)}}
async function post(url,auth,body){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:auth},body,signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('El servidor respondió '+response.status+'.');}
async function save(){if(saveBusy)return;try{LandingModel.validate(config,baseURL.href);if(loadFailed)throw Error('Recargá la versión publicada antes de guardar, para no sobrescribir cambios que no pudimos leer.');if(!bridge.jwt)throw Error('Tu sesión venció. Volvé a ingresar al administrador.');if(!bridge.cfAuth)throw Error('Falta la conexión de publicación del sitio.');saveBusy=true;root().querySelectorAll('.la-toolbar button,.la-editor input,.la-editor textarea,.la-editor button').forEach(b=>b.disabled=true);status('Guardando y publicando…');const snapshot=JSON.stringify({...config,updatedAt:new Date().toISOString()});await post(bridge.clientesURL+'/config/'+KEY,'Bearer '+bridge.jwt,snapshot);try{await post(bridge.cfURL+'/'+KEY,bridge.cfAuth,snapshot)}catch(e){throw Error('El contenido quedó guardado, pero no se pudo actualizar la página pública. Volvé a publicar. '+e.message)}try{localStorage.setItem(KEY,snapshot);localStorage.removeItem(DRAFT)}catch{}dirty=false;status('Cambios publicados en la landing de XV.')}catch(error){status(error.message,true)}finally{saveBusy=false;root().querySelectorAll('.la-toolbar button,.la-editor input,.la-editor textarea,.la-editor button').forEach(b=>b.disabled=false)}}
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===iframe?.contentWindow&&event.data?.type==='landing-ready')preview()});window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
window.LandingAdmin={open};
})();
