import {guideAnswer} from './crbot-core.mjs';
const preview=new URLSearchParams(location.search).get('preview')==='1';
let config=window.CRBotConfig||{},history=[],lastPack='',busy=false,controller;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n}
const launch=el('button','crbot-launch');launch.type='button';launch.setAttribute('aria-controls','crbot-panel');launch.setAttribute('aria-expanded','false');launch.innerHTML='<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 7V4"/><circle cx="12" cy="3" r="1"/><rect x="4" y="7" width="16" height="13" rx="4"/><path d="M4 12H2v4h2M20 12h2v4h-2M9 16h6"/><circle cx="8.5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="15.5" cy="12" r="1" fill="currentColor" stroke="none"/></svg>';const launchText=el('span','crbot-launch-label','Consultale a RomeBot');launch.append(launchText);const bubble=el('span','crbot-bubble','Consultame aquí');bubble.setAttribute('aria-hidden','true');launch.append(bubble);
const panel=el('section','crbot-panel');panel.id='crbot-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Chat con RomeBot');
const head=el('div','crbot-head'),heading=el('div'),name=el('strong','','RomeBot'),subtitle=el('small','','Asistente virtual · Servicios');heading.append(name,subtitle);const close=el('button','crbot-close','×');close.type='button';close.setAttribute('aria-label','Cerrar chat');head.append(heading,close);
const log=el('div','crbot-log');log.setAttribute('role','log');log.setAttribute('aria-live','polite');log.setAttribute('aria-relevant','additions');log.setAttribute('aria-label','Conversación');
const suggestions=el('div','crbot-suggestions');for(const label of ['Comparar packs','¿Qué incluye Portrait?','¿Cuánto cuesta?']){const b=el('button','',label);b.type='button';b.addEventListener('click',()=>ask(label));suggestions.append(b)}
const status=el('p','crbot-status');status.setAttribute('role','status');
const actions=el('div','crbot-actions');for(const [intent,label] of [['cita','Reservar cita'],['info','Pedir información']]){const b=el('button','',label);b.type='button';b.addEventListener('click',()=>{hide();document.querySelector('main [data-intent="'+intent+'"]')?.click()});actions.append(b)}
const form=el('form','crbot-compose'),input=el('input');input.type='text';input.maxLength=800;input.placeholder='Escribí tu consulta…';input.setAttribute('aria-label','Tu consulta para RomeBot');input.autocomplete='off';input.required=true;const send=el('button','','↑');send.type='submit';send.setAttribute('aria-label','Enviar consulta');form.append(input,send);form.addEventListener('submit',e=>{e.preventDefault();ask(input.value)});
const foot=el('p','crbot-foot','No compartas datos sensibles. Para dejar tu nombre y email, usá “Pedir información”.');panel.append(head,log,suggestions,status,actions,form,foot);document.body.append(launch,panel);
function add(role,text){const item=el('div','crbot-message'+(role==='user'?' user':''),text);item.setAttribute('aria-label',role==='user'?'Vos':'RomeBot');log.append(item);while(log.children.length>40)log.firstChild.remove();log.scrollTop=log.scrollHeight;return item}
function welcome(){return config.bot?.welcome||'¡Hola! Soy RomeBot, el asistente virtual de Cristian Romero Producciones. Puedo orientarte sobre nuestros servicios y ayudarte a comparar los packs. ¿Qué te gustaría saber?'}
function show(){panel.hidden=false;launch.setAttribute('aria-expanded','true');if(!log.children.length)add('assistant',welcome());input.focus()}
function hide(){panel.hidden=true;launch.setAttribute('aria-expanded','false');launch.focus()}
launch.addEventListener('click',()=>panel.hidden?show():hide());close.addEventListener('click',hide);panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hide()}});
function settings(next){config=next||{};const enabled=config.bot?.enabled!==false;launch.hidden=!enabled;if(!enabled){panel.hidden=true;launch.setAttribute('aria-expanded','false');controller?.abort()}launchText.textContent=config.bot?.label||'Consultale a RomeBot';launch.title=launchText.textContent;launch.setAttribute('aria-label',launchText.textContent);if(log.children.length===1&&history.length===0)log.firstChild.textContent=welcome()}
window.addEventListener('crbot-config',e=>settings(e.detail));settings(config);
async function ask(raw){const question=raw.trim();if(!question||busy)return;input.value='';busy=true;send.disabled=true;suggestions.querySelectorAll('button').forEach(b=>b.disabled=true);add('user',question);status.textContent='RomeBot está respondiendo…';const local=guideAnswer(question,config,lastPack);let answer=local;
try{if(config.bot?.endpoint&&!preview){const url=new URL(config.bot.endpoint);if(url.protocol!=='https:')throw Error('endpoint');controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question,history:history.slice(-8),lastPack}),signal:controller.signal});if(!r.ok)throw Error('request');const data=await r.json();if(typeof data.answer!=='string'||!data.answer.trim()||data.answer.length>12000)throw Error('response');answer=data}catch{status.textContent='Ahora te respondo con la guía de servicios disponible.'}finally{clearTimeout(timeout)}}if(config.bot?.enabled===false)return;add('assistant',answer.answer);history.push({role:'user',content:question},{role:'assistant',content:answer.answer});history=history.slice(-8);if(answer.pack)lastPack=answer.pack;if(!status.textContent.startsWith('Ahora'))status.textContent=preview?'Vista previa · Respuestas de la guía de servicios':answer.mode==='guide'?'Respuesta de la guía de servicios':'';
}finally{busy=false;send.disabled=false;suggestions.querySelectorAll('button').forEach(b=>b.disabled=false);log.scrollTop=log.scrollHeight}}
