(function(root){
'use strict';
const groups=[['brand','Marca y navegación','header'],['hero','Primera pantalla','.hero'],['ribbon','Franja de presentación','.ribbon'],['intro','Quién soy','#conoceme'],['experiences','Presentación de propuestas','.section-head'],['event','CR Event','#event'],['portrait','CR Portrait','#portrait'],['editorial','CR Editorial','#editorial'],['cinematic','CR Cinematic','#cinematic'],['conditions','Condiciones comunes','.common'],['process','Cómo trabajamos','.process'],['faq','Preguntas frecuentes','.faq'],['contact','Botones de contacto','#consulta'],['footer','Pie de página','footer']];
function driveId(raw){const value=String(raw||'').trim();if(/^[\w-]{20,}$/.test(value))return {id:value};try{const u=new URL(value);if(u.protocol!=='https:'||!['drive.google.com','docs.google.com','lh3.googleusercontent.com'].includes(u.hostname))return null;const id=u.pathname.match(/\/(?:file\/)?d\/([\w-]+)/)?.[1]||u.searchParams.get('id');if(!id||!/^[-\w]+$/.test(id))return null;return {id,resourcekey:u.searchParams.get('resourcekey')}}catch{return null}}
function imageURL(raw,base){if(!raw)return '';const drive=driveId(raw);if(drive){const u=new URL('https://drive.google.com/thumbnail');u.searchParams.set('id',drive.id);u.searchParams.set('sz','w1600');if(drive.resourcekey)u.searchParams.set('resourcekey',drive.resourcekey);return u.href}try{const u=new URL(raw,base);return u.protocol==='https:'||(u.origin===new URL(base).origin&&u.protocol==='http:')?u.href:''}catch{return ''}}
function videoURL(raw){const drive=driveId(raw);if(drive){const u=new URL('https://drive.google.com/file/d/'+drive.id+'/preview');if(drive.resourcekey)u.searchParams.set('resourcekey',drive.resourcekey);return {type:'embed',url:u.href}}try{const u=new URL(raw);if(u.protocol!=='https:')return null;let id;if(['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:embed|shorts)\/([\w-]+)/)?.[1];else if(u.hostname==='youtu.be')id=u.pathname.slice(1);if(id&&/^[\w-]{11}$/.test(id))return {type:'embed',url:'https://www.youtube-nocookie.com/embed/'+id};if(/\.(mp4|webm)$/i.test(u.pathname))return {type:'file',url:u.href};return null}catch{return null}}
function collect(doc){const fields=[];for(const [group,,selector] of groups){let counter=0;doc.querySelectorAll(selector).forEach(section=>{const walker=doc.createTreeWalker(section,4);let node;while((node=walker.nextNode())){const parent=node.parentElement,text=node.nodeValue.trim();if(!text||parent.closest('script,style,select,ul,.pack-nav,[aria-hidden],#year')||['01','02','03','04','↗'].includes(text))continue;const el=parent.closest('h1,h2,h3,p,a,button,label,summary,small,strong,em')||parent;const label=parent.tagName==='EM'?'Título destacado':/^H[123]$/.test(el.tagName)?'Título':el.classList.contains('eyebrow')?'Antetítulo':['A','BUTTON'].includes(el.tagName)?'Texto del botón':el.tagName==='SUMMARY'?'Pregunta':el.tagName==='LABEL'?'Etiqueta':'Texto';fields.push({key:group+'.text.'+(counter++),group,label,kind:text.length>90?'textarea':'text',value:text,node});}
section.querySelectorAll('img').forEach((img,i)=>{fields.push({key:group+'.image.'+i,group,label:'Imagen',kind:'image',value:img.getAttribute('src'),node:img,attr:'src'});fields.push({key:group+'.alt.'+i,group,label:'Descripción de la imagen',kind:'text',value:img.alt,node:img,attr:'alt'});fields.push({key:group+'.position.'+i,group,label:'Encuadre vertical (%)',kind:'number',value:40,node:img,attr:'position'});});
section.querySelectorAll('ul').forEach((ul,i)=>fields.push({key:group+'.list.'+i,group,label:'Prestaciones (una por línea)',kind:'textarea',value:Array.from(ul.children,x=>x.textContent).join('\n'),node:ul,attr:'list'}));
section.querySelectorAll('input[placeholder]').forEach((input,i)=>fields.push({key:group+'.placeholder.'+i,group,label:'Ayuda del campo',kind:'text',value:input.placeholder,node:input,attr:'placeholder'}));
});}
return fields;}
function defaults(doc){return {version:1,formLayout:2,values:Object.fromEntries(collect(doc).map(f=>[f.key,f.value])),whatsapp:'5491162557763',bot:{enabled:true,label:'Consultale a RomeBot',welcome:'¡Hola! Soy RomeBot, el asistente virtual de Cristian Romero Producciones. Puedo orientarte sobre nuestros servicios y ayudarte a comparar los packs. ¿Qué te gustaría saber?',endpoint:'',prices:'',booking:'',delivery:'',weddings:'',extra:'',fallback:'Perdón, no estoy seguro de haber entendido tu consulta. ¿Te puedo ayudar con alguna de estas opciones?'},logo:'',videos:{presentacion:'',event:'',portrait:'',editorial:'',cinematic:''},videoLabels:{presentacion:'Conocé a Cristian',event:'Conocé CR Event',portrait:'Conocé CR Portrait',editorial:'Conocé CR Editorial',cinematic:'Conocé CR Cinematic'},hidden:{},colors:{bg:'#111110',panel:'#1a1a17',gold:'#c9a84c',ink:'#f1ede4',muted:'#b9b7ae'},form:{citaTitle:'Reservar una cita con Cristian',infoTitle:'Pedir más información',citaDescription:'Dejanos tus datos para coordinar una cita con Cristian.',infoDescription:'Dejanos tus datos y te contamos más sobre nuestras propuestas.',citaSuccess:'Recibimos tu solicitud. Te contactaremos por email para coordinar el día y horario de la cita.',infoSuccess:'Recibimos tu consulta. Te contactaremos por email con más información.',error:'No pudimos enviar tu solicitud. Por favor, intentá nuevamente.'},seo:{title:doc.title,description:doc.querySelector('meta[name="description"]').content}};}
function merge(base,data){
if(!data||data.version!==1)return structuredClone(base);
const values={...(data.values||{})};
// Conservar las etiquetas editadas al migrar del formulario de tres campos.
if(data.formLayout!==2){
for(const key of Object.keys(values))if(/^form\.text\.\d+$/.test(key))delete values[key];
for(const [key,value] of Object.entries(data.values||{})){const m=key.match(/^form\.text\.(\d+)$/);if(!m)continue;const index=Number(m[1]);if(index===0)values[key]=value==='Nombre'?'Nombre y apellido':value;else if(index>=2)values['form.text.'+(index-1)]=value;}
}
const out={...base,...data,formLayout:2};
for(const k of ['values','videos','videoLabels','hidden','colors','seo','form','bot'])out[k]={...base[k],...(k==='values'?values:data[k]&&typeof data[k]==='object'?data[k]:{})};
// Reparar también los textos originales si se recupera un borrador anterior.
for(const [key,value] of Object.entries(out.form))if(typeof value==='string')out.form[key]=value.replaceAll('m?s','más').replaceAll('informaci?n','información').replaceAll('d?a','día').replaceAll('intent?','intentá');
return out;
}
function validate(data,base){if(data.bot?.endpoint){let u;try{u=new URL(data.bot.endpoint)}catch{throw Error('Revisá la dirección de conexión de RomeBot.')}if(u.protocol!=='https:')throw Error('La conexión de RomeBot debe usar HTTPS.');}if(String(data.bot?.extra||'').length>10000)throw Error('La información adicional de RomeBot admite hasta 10.000 caracteres.');if(!/^\d{10,15}$/.test(data.whatsapp||''))throw Error('Revisá el número de WhatsApp: código de país y número, solo dígitos.');for(const [slot,url] of Object.entries(data.videos||{}))if(url&&!videoURL(url))throw Error('Revisá el video de '+slot+': usá un enlace de archivo de Drive.');if(data.logo&&!imageURL(data.logo,base))throw Error('Revisá el enlace del logo.');for(const [key,value] of Object.entries(data.values||{})){if(key.includes('.image.')&&!imageURL(value,base))throw Error('Revisá el enlace de imagen en '+key.split('.')[0]+'.');if(key.includes('.position.')&&(!Number.isFinite(Number(value))||Number(value)<0||Number(value)>100))throw Error('El encuadre debe estar entre 0 y 100.');}for(const color of Object.values(data.colors||{}))if(!/^#[\da-f]{6}$/i.test(color))throw Error('Revisá los colores.');return true;}
root.LandingModel={groups,driveId,imageURL,videoURL,collect,defaults,merge,validate};
})(typeof window==='undefined'?globalThis:window);
