(()=>{'use strict';
const M=LandingModel,base=M.defaults(document),fields=M.collect(document),preview=new URLSearchParams(location.search).get('preview')==='1';
let config=structuredClone(base);const dialog=document.getElementById('video-dialog'),player=document.getElementById('player');
const query=new URLSearchParams(location.search),attribution={};for(const key of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']){const v=query.get(key);if(v)attribution[key]=v.slice(0,160)}
function track(event,props={}){if(preview)return;window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,landing:'xv',...attribution,...props})}
function packName(id){return document.querySelector('#'+id+' h3')?.textContent||id}
function render(data){config=M.merge(base,data);window.CRBotConfig=config;window.dispatchEvent(new CustomEvent('crbot-config',{detail:config}));for(const field of fields){const value=String(config.values[field.key]??field.value),el=field.node;if(field.attr==='src'){const src=M.imageURL(value,location.href);if(src)el.src=src}else if(field.attr==='position'){const n=Number(value);if(n>=0&&n<=100)el.style.objectPosition='center '+n+'%'}else if(field.attr==='list'){el.replaceChildren(...value.split('\n').map(s=>s.trim()).filter(Boolean).map(text=>{const li=document.createElement('li');li.textContent=text;return li}))}else if(field.attr)el.setAttribute(field.attr,value);else el.nodeValue=value;}
for(const [key,value] of Object.entries(config.colors))if(['bg','panel','gold','ink','muted'].includes(key)&&/^#[\da-f]{6}$/i.test(value))document.documentElement.style.setProperty('--'+key,value);
for(const [key,,selector] of M.groups)document.querySelectorAll(selector).forEach(el=>el.hidden=!!config.hidden[key]);
const brand=document.querySelector('.brand'),monogram=brand.querySelector('.monogram');let logo=brand.querySelector('.brand-image');const logoURL=M.imageURL(config.logo,location.href);if(logoURL){if(!logo){logo=document.createElement('img');logo.className='brand-image';logo.alt='Logo de Cristian Romero Producciones';logo.style.cssText='width:65px;height:48px;object-fit:contain';logo.addEventListener('error',()=>{logo.hidden=true;monogram.hidden=false});brand.prepend(logo)}logo.src=logoURL;logo.hidden=false;monogram.hidden=true}else{if(logo)logo.hidden=true;monogram.hidden=false}
document.title=config.seo.title;document.querySelector('meta[name="description"]').content=config.seo.description;
for(const id of ['event','portrait','editorial','cinematic']){const nav=document.querySelector('.pack-nav a[href="#'+id+'"]');nav.hidden=!!config.hidden[id];nav.textContent=packName(id);}
document.querySelectorAll('[data-video]').forEach(slot=>{slot.querySelector('button')?.remove();const key=slot.dataset.video,media=M.videoURL(config.videos[key]);if(!media)return;const button=document.createElement('button');button.type='button';const label=config.videoLabels[key]||'Ver video';button.setAttribute('aria-label','Reproducir: '+label);const play=document.createElement('span');play.className='play';play.setAttribute('aria-hidden','true');play.textContent='▶';const text=document.createElement('span');text.className='video-label';text.textContent=label;button.append(play,text);button.addEventListener('click',()=>{document.getElementById('video-title').textContent=label;const el=document.createElement(media.type==='file'?'video':'iframe');el.src=media.url;if(media.type==='file'){el.controls=true;el.playsInline=true;el.preload='metadata'}else{el.title=label;el.allow='fullscreen; picture-in-picture';el.allowFullscreen=true;el.referrerPolicy='strict-origin-when-cross-origin'}player.replaceChildren(el);dialog.showModal();track('xv_video_open',{video:key})});slot.append(button)});
}
const leadDialog=document.getElementById('lead-dialog'),leadForm=document.getElementById('lead-form'),leadStatus=document.getElementById('lead-status');let leadIntent='info',leadPack='',sending=false;
document.querySelectorAll('[data-intent]').forEach(button=>button.addEventListener('click',()=>{if(sending)return;leadIntent=button.dataset.intent;leadPack=(button.dataset.pack||'').toLowerCase();leadForm.hidden=false;leadStatus.textContent='';document.getElementById('lead-title').textContent=config.form[leadIntent+'Title'];document.getElementById('lead-description').textContent=config.form[leadIntent+'Description'];leadDialog.showModal();track('xv_form_open',{intent:leadIntent,pack:leadPack||'general'})}));
leadDialog.querySelector('.close').addEventListener('click',()=>{if(!sending)leadDialog.close()});leadDialog.addEventListener('cancel',event=>{if(sending)event.preventDefault()});
const mailDefaults={emailjsKey:'odUJtdh1Z0U27ZkaN',emailjsServiceId:'service_35rtklk',emailjsContactTemplate:'template_bdpe4yq'};
let mailSettings=mailDefaults;
if(!preview)fetch('https://web.cristian-romero-digital.workers.dev/crd_settings',{cache:'no-store',signal:AbortSignal.timeout(7000)}).then(r=>r.ok?r.json():null).then(data=>{if(data)mailSettings={emailjsKey:data.emailjsKey||mailDefaults.emailjsKey,emailjsServiceId:data.emailjsServiceId||mailDefaults.emailjsServiceId,emailjsContactTemplate:data.emailjsContactTemplate||mailDefaults.emailjsContactTemplate}}).catch(()=>{});
leadForm.addEventListener('submit',async event=>{event.preventDefault();if(sending||!leadForm.reportValidity()||document.getElementById('lead-company').value)return;const fullName=document.getElementById('lead-name').value.trim(),email=document.getElementById('lead-email').value.trim();if(!fullName){leadStatus.textContent='Completá tu nombre y apellido.';return}if(preview){leadStatus.textContent='Vista previa: el formulario funciona, pero no se envían consultas desde el editor.';return}const submit=leadForm.querySelector('[type="submit"]');sending=true;submit.disabled=true;leadStatus.textContent='Enviando…';const intent=leadIntent,pack=leadPack;const data={name:fullName,email,phone:'',service:'XV · '+(intent==='cita'?'Solicitud de cita con Cristian':'Más información')+(pack?' · '+packName(pack):''),event_date:'',message:(intent==='cita'?'Quiero coordinar una cita con Cristian.':'Quiero recibir más información sobre las propuestas de XV.')+(pack?' Me interesa '+packName(pack)+'.':'')+'\nOrigen: landing XV'+Object.entries(attribution).map(([k,v])=>'\n'+k+': '+v).join(''),time:new Date().toLocaleString('es-AR')};try{const response=await fetch('https://api.emailjs.com/api/v1.0/email/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service_id:mailSettings.emailjsServiceId,template_id:mailSettings.emailjsContactTemplate,user_id:mailSettings.emailjsKey,template_params:data}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('send');leadForm.hidden=true;leadForm.reset();leadStatus.textContent=config.form[intent+'Success'];track('xv_lead_sent',{intent,pack:pack||'general'})}catch{leadStatus.textContent=config.form.error}finally{sending=false;submit.disabled=false}});
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>player.replaceChildren());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
document.getElementById('year').textContent=new Date().getFullYear();
if(preview){render(base);window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===parent&&event.data?.type==='landing-preview')render(event.data.config)});parent.postMessage({type:'landing-ready'},location.origin)}else{render(base);fetch('https://web.cristian-romero-digital.workers.dev/crd_landing_xv',{cache:'no-store',signal:AbortSignal.timeout(7000)}).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(data=>{if(data)render(data)}).catch(()=>{});track('xv_landing_view')}
})();
